#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
==============================================================================
🌟 位姿卡尔曼滤波效果对比分析脚本 (plot_pose_comparison.py)
读取 C++ 侧输出的 CSV，利用 Pandas 和 Matplotlib 对 6 DoF 姿态数据
进行渲染，直观展示卡尔曼滤波在处理 PnP 抖动及瞬间丢失时的平滑性能。
==============================================================================
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import argparse
import sys


def parse_args():
    # 【核心修复】：标准实例化 ArgumentParser
    parser = argparse.ArgumentParser(description='Kalman Filter Smoothing Performance Analyzer')

    # 【路径修改点】：已根据您的运行环境为您预设了 D 盘工作目录，请确认文件名是否为 KF.csv
    parser.add_argument('-i', '--input', type=str, default=r"D:\work\2-square\KF.csv",
                        help="Path to the input CSV file generated by C++ tracking system")
    parser.add_argument('-s', '--save', type=str, default="kf_comparison.png",
                        help="Path to save the output plot")

    return parser.parse_args()


def main():
    args = parse_args()

    # 1. 读取 CSV 数据
    try:
        df = pd.read_csv(args.input)
    except Exception as e:
        print(f"❌ 读取 CSV 失败: {e}\n请检查代码第 24 行的路径是否填写正确！\n当前尝试读取的路径为: {args.input}")
        sys.exit(1)

    # 清理那些丢失目标的帧 (0 填充) 导致的坐标骤降，避免画图拉跨
    # 将所有值为 0 的记录替换为 NaN，方便 Matplotlib 画图时断开而不是画一条线到0
    df_clean = df.replace(0.0000, np.nan)

    frames = df_clean['Video_Frame']

    # 2. 创建 3x2 的子图矩阵结构 (对应 X, Y, Z, Roll, Pitch, Yaw)
    fig, axes = plt.subplots(3, 2, figsize=(16, 12), dpi=150)
    fig.suptitle('Kalman Filter Smoothing Performance (Raw PnP vs KF)', fontsize=18, fontweight='bold', y=0.98)

    # 预定义需要绘制的数据对和标题
    plot_configs = [
        {'ax': axes[0, 0], 'raw': 'raw_x', 'kf': 'kf_x', 'title': 'Translation X (East)', 'ylabel': 'Meters'},
        {'ax': axes[0, 1], 'raw': 'raw_roll', 'kf': 'kf_roll', 'title': 'Rotation Roll', 'ylabel': 'Degrees'},
        {'ax': axes[1, 0], 'raw': 'raw_y', 'kf': 'kf_y', 'title': 'Translation Y (North)', 'ylabel': 'Meters'},
        {'ax': axes[1, 1], 'raw': 'raw_pitch', 'kf': 'kf_pitch', 'title': 'Rotation Pitch', 'ylabel': 'Degrees'},
        {'ax': axes[2, 0], 'raw': 'raw_z', 'kf': 'kf_z', 'title': 'Translation Z (Up / Distance)', 'ylabel': 'Meters'},
        {'ax': axes[2, 1], 'raw': 'raw_yaw', 'kf': 'kf_yaw', 'title': 'Rotation Yaw (Heading)', 'ylabel': 'Degrees'}
    ]

    # 3. 循环遍历绘制每个子图
    for cfg in plot_configs:
        ax = cfg['ax']

        # 绘制原始 PnP 散点/微弱细线 (代表带噪测量)
        ax.plot(frames, df_clean[cfg['raw']], color='lightcoral', marker='.', linestyle='--', linewidth=1, markersize=3,
                alpha=0.6, label='Raw PnP (Noisy)')

        # 绘制 KF 滤波后的平滑粗线 (代表状态估计)
        ax.plot(frames, df_clean[cfg['kf']], color='dodgerblue', linestyle='-', linewidth=2.5, alpha=0.9,
                label='Kalman Filtered')

        # 图表美化设置
        ax.set_title(cfg['title'], fontsize=12, fontweight='bold', pad=10)
        ax.set_xlabel('Frame Index', fontsize=10)
        ax.set_ylabel(cfg['ylabel'], fontsize=10)
        ax.grid(True, linestyle=':', alpha=0.7)
        ax.legend(loc='best', fontsize=9)

        # 设定背景色微调
        ax.set_facecolor('#F8F9FA')

    # 4. 自动调整布局防重叠并保存
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])

    plt.savefig(args.save, bbox_inches='tight')
    print(f"✅ 图表绘制完成！已保存为高清图片: {args.save}")

    # 交互式展示
    plt.show()


if __name__ == "__main__":
    main()